#!/bin/bash
set -euo pipefail
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

ynh_script_progression --message="Removing NGINX config" --time
ynh_remove_nginx_config

ynh_script_progression --message="Stopping services" --time
systemctl stop zammad zammad-web zammad-worker zammad-websocket || true

ynh_script_progression --message="Purging packages" --time
DEBIAN_FRONTEND=noninteractive apt-get purge -y zammad || true
apt-get autoremove -y --purge || true

ynh_script_progression --message="Cleaning APT source" --time
rm -f /etc/apt/sources.list.d/zammad.list /usr/share/keyrings/zammad-archive-keyring.gpg || true
apt-get update || true

ynh_script_progression --message="Unregistering web path" --time
ynh_webpath_remove --app="$app"
